name: Mirroring to CodeCommit

on: [push, delete]

jobs:
  to_codecommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ssh://git-codecommit.us-west-2.amazonaws.com/v1/repos/python-uefivars
          ssh_private_key:
            ${{ secrets.CC_USER_PKEY }}
          ssh_username:
            ${{ secrets.CC_USER_PKEY_ID }}
